from utils import get_db_connection



songurls={
  "God's Plan": "https://www.youtube.com/watch?v=xpVfcZ0ZcFM",
  "SAD!": "https://www.youtube.com/watch?v=pgN-vvVVxMA",
  "rockstar (feat. 21 Savage)": "https://www.youtube.com/watch?v=wAumf1WLoh4",
  "Psycho (feat. Ty Dolla $ign)": "https://youtu.be/au2n7VVGv_c?si=bgnnXLdi9vgKkZHq",
  "In My Feelings": "https://www.youtube.com/watch?v=DRS_PpOrUZ4",
  "Better Now": "https://www.youtube.com/watch?v=UYwF-jdcVjY",
  "I Like It": "https://www.youtube.com/watch?v=xTlNMmZKwpA",
  "One Kiss (with Dua Lipa)": "https://www.youtube.com/watch?v=DkeiKbqa02g",
  "IDGAF": "https://youtu.be/Mgfe5tIwOj0?si=Cipg6GBferS2Nyel",
  "FRIENDS": "https://youtu.be/jzD_yyEcp0M?si=W9cguJnlVOBslq1C",
  "Havana": "https://youtu.be/BQ0mxQXmLsk?si=S7pIE4llBQo5um1G",
  "Lucid Dreams": "https://youtu.be/mzB1VGEGcSU?si=x8TbieVe9UDGRrR6",
  "Nice For What": "https://www.youtube.com/watch?v=U9BwWKXjVaI",
  "Girls Like You (feat. Cardi B)": "https://www.youtube.com/watch?v=aJOTlE1K90k",
  "The Middle": "https://www.youtube.com/watch?v=M3mJkSqZbX4",
  "All The Stars (with SZA)": "https://www.youtube.com/watch?v=JQbjS0_ZfJ0",
  "no tears left to cry": "https://www.youtube.com/watch?v=ffxKSjUwKdU",
  "X": "https://youtu.be/_I_D_8Z4sJE?si=TgH1Pxgy7Lha5CM4",
  "Moonlight": "https://youtu.be/8F7Q-4PZCjA?si=YW0d4a9quACZQUbX",
  "Look Alive (feat. Drake)": "https://youtu.be/NV-3s2wwC8c?si=JmLOdpqkhz4YzQn7",
  "These Days (feat. Jess Glynne, Macklemore & Dan Caplen)": "https://youtu.be/pjTj-_55WZ8?si=8WYf-l_Qt-mkWg9J",
  "Te Bote - Remix": "https://www.youtube.com/watch?v=9jI-z9QN6g8",
  "Mine": "https://youtu.be/Gc71AmT_b2k?si=tZgdVKFbDL3mE7wQ",
  "Youngblood": "https://youtu.be/-RJSbO8UZVY?si=jDMwD_SzKE84Y5Pi",
  "New Rules": "https://www.youtube.com/watch?v=k2qgadSvNyU",
  "Shape of You": "https://www.youtube.com/watch?v=JGwWNGJdvx8",
  "Love Lies (with Normani)": "https://youtu.be/xYtsL9znopI?si=45eVHv1-2JPF1wWB",
  "Meant to Be (feat. Florida Georgia Line)": "https://www.youtube.com/watch?v=zDo0H8Fm7d0",
  "Jocelyn Flores": "https://www.youtube.com/watch?v=FAucVNRx_mU",
  "Perfect": "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
  "Taste (feat. Offset)": "https://youtu.be/LjxulQ1bEWg?si=Uyw4XHTK2iEmyhg8",
  "Solo (feat. Demi Lovato)": "https://youtu.be/8JnfIa84TnU?si=YgK5qkIDHvTy0Gsk",
  "I Fall Apart": "https://youtu.be/nqfVoTMEosw?si=CJZczA9RG9QP4Abv",
  "Nevermind": "https://youtu.be/naW6-WxmMiU?si=pp1U8OFd32LWooUG",
  "Echame La Culpa": "https://www.youtube.com/watch?v=TyHvyGVs42U",
  "Eastside (with Halsey & Khalid)": "https://youtu.be/56WBK4ZK_cw?si=nKqS_7NbY-IrXMqZ",
  "Never Be the Same": "https://www.youtube.com/watch?v=Ph54wQG8ynk",
  "Wolves": "https://youtu.be/cH4E_t3m3xM?si=cdLph9tdpikZ7vIg",
  "changes": "https://www.youtube.com/watch?v=f0bbDFRYD_A",
  "In My Mind": "https://www.youtube.com/watch?v=W9P_qUnMaFg",
  "River (feat. Ed Sheeran)": "https://www.youtube.com/watch?v=3BXDsVD6O10",
  "Dura": "https://youtu.be/sGIm0-dQd8M?si=0taiDOT2fgaSkPFQ",
  "SICKO MODE": "https://www.youtube.com/watch?v=6ONRf7h3Mdk",
  "Thunder": "https://www.youtube.com/watch?v=fKopy74weus",
  "Me Niego": "https://youtu.be/JyqD_zfXfi8?si=Kxj9e54A7MNnquLW",
  "Jackie Chan": "https://youtu.be/6DaL-Z4dwzI?si=qhsaUxRDSioo9DCf",
  "Finesse (Remix) [feat. Cardi B]": "https://www.youtube.com/watch?v=LsoLEjrDogU",
  "Back To You - From 13 Reasons Why": "https://youtu.be/ulNswX3If6U?si=TMDhiwVv1mX511b9",
  "Let You Down": "https://www.youtube.com/watch?v=fbHbTBP_u7U",
  "Call Out My Name": "https://youtu.be/M4ZoCHID9GI?si=LGnpGlaTy0wbYU6X",
  "Ric Flair Drip (& Metro Boomin)": "https://www.youtube.com/watch?v=LPTlvQ1Zet0",
  "Happier": "https://www.youtube.com/watch?v=m7Bc3pLyij0",
  "Too Good At Goodbyes": "https://www.youtube.com/watch?v=J_ub7Etch2U",
  "Freaky Friday (feat. Chris Brown)": "https://youtu.be/aZla1ttZHaw?si=q0JPaCH7cDCCxMrg",
  "Believer": "https://www.youtube.com/watch?v=7wtfhZwyrcc",
  "FEFE (feat. Nicki Minaj & Murda Beatz)": "https://www.youtube.com/watch?v=V_MXGdSBbAI",
  "Rise": "https://youtu.be/btrzs54s1Rc?si=jgKdP3yW8xieM9ep",
  "Body (feat. brando)": "https://youtu.be/IetIg7y5k3A?si=qVORDZtUgSfJO5dm",
  "XO TOUR Llif3": "https://www.youtube.com/watch?v=WrsFXgQk5UI",
  "Sin Pijama": "https://www.youtube.com/watch?v=zEf423kYfqk",
  "2002": "https://www.youtube.com/watch?v=Il-an3K9pjg",
  "Nonstop": "https://youtu.be/lJTRVX9R5EA?si=81QLMYAq9Sw6SWid",
  "Fuck Love (feat. Trippie Redd)": "https://youtu.be/wXuFG8uQpZ8?si=fMzZgwqpRlrp2KOC",
  "In My Blood": "https://youtu.be/36tggrpRoTI?si=eyYGSkcQt3VArwi2",
  "Silence": "https://www.youtube.com/watch?v=Tx1sqYc3qas",
  "God is a woman": "https://www.youtube.com/watch?v=kHLHSlExFis",
  "Dejala que vuelva (feat. Manuel Turizo)": "https://youtu.be/y7d9VLRO3vc?si=_9EroswtTfo2kKcp",
  "Flames": "https://youtu.be/J75enyWdbBM?si=mff8mUhRbvGwRI38",
  "What Lovers Do": "https://youtu.be/5Wiio4KoGe8?si=34yBH-TvkNneeZmG",
  "Taki Taki (with Selena Gomez, Ozuna & Cardi B)": "https://www.youtube.com/watch?v=ixkoVwKQaJg",
  "Let Me Go (with Alesso, Florida Georgia Line & watt)": "https://youtu.be/BQ_0QLL2gqI?si=WaxL3tiwfnDm5Hf5",
  "Feel It Still": "https://www.youtube.com/watch?v=pBkHHoOIIn8",
  "Pray For Me (with Kendrick Lamar)": "https://www.youtube.com/watch?v=K5xERXE7pxI",
  "Walk It Talk It": "https://youtu.be/fGqdIPer-ms?si=nE88B_jrlSMNsnBK",
  "Him & I (with Halsey)": "https://www.youtube.com/watch?v=SA7AIQw-7Ms",
  "Candy Paint": "https://youtu.be/a2wERrLIYmI?si=uk3peV46h54xC4Yj",
  "Congratulations": "https://www.youtube.com/watch?v=SC4xMk98Pdc",
  "1, 2, 3 (feat. Jason Derulo & De La Ghetto)": "https://youtu.be/p03TIGqEc8o?si=Qcx_CaQVgYovwJj-",
  "Criminal": "https://youtu.be/s6b33PTbGxk?si=r0z9LD0YMk4CxE9p",
  "Plug Walk": "https://youtu.be/ToY6sjSV8h8?si=96G2Htmi10A-dMiT",
  "lovely (with Khalid)": "https://www.youtube.com/watch?v=V1Pl8CzNzCw",
  "Stir Fry": "https://youtu.be/HI-mXMr8glQ?si=q7mvSn_HirFC_DMb",
  "HUMBLE.": "https://www.youtube.com/watch?v=tvTRZJ-4EyI",
  "Vaina Loca": "https://youtu.be/bx-fuY7LpSU?si=wAYq_H8YFlUvgXyJ",
  "Perfect Duet (Ed Sheeran & Beyoncé)": "https://www.youtube.com/watch?v=817P8W8-mGE",
  "Corazon (feat. Nego do Borel)": "https://youtu.be/GmHrjFIWl6U?si=Gcmg32hUDvEqt3Pg",
  "Young Dumb & Broke": "https://youtu.be/IPfJnp1guPc?si=o3o39nbpJ3Picj6J",
  "Siguelo Bailando": "https://youtu.be/Dvpd9_5vuks?si=ZTRuS38Mi5loCyTW",
  "Downtown": "https://youtu.be/wlS6Ix7mA0w?si=HfYeaSKQe_r_BWtb",
  "Bella": "https://youtu.be/UA0YaA06Puo?si=BrqtUX76mjVXmC07",
  "Promises (with Sam Smith)": "https://www.youtube.com/watch?v=kkLk2XWMBf8",
  "Yes Indeed": "https://youtu.be/2agCnyknvJA?si=gFX3_xZEi12SOfRZ",
  "I Like Me Better": "https://youtu.be/BcqxLCWn-CE?si=Yqh4BcFj55AylCzh",
  "This Is Me": "https://www.youtube.com/watch?v=CjxugyZCfuw",
  "Everybody Dies In Their Nightmares": "https://youtu.be/7JGDWKJfgxQ?si=Rj02ImUw0riVDnqH",
  "Rewrite The Stars": "https://youtu.be/pRfmrE0ToTo?si=v93HP7qC2B5rWcUu",
  "I Miss You (feat. Julia Michaels)": "https://youtu.be/uZs1AHQBz24?si=pmqhdZkSAjjq4wyS",
  "No Brainer": "https://youtu.be/kxloC1MKTpg?si=EQG0Anh61bXT52PE",
  "Dusk Till Dawn - Radio Edit": "https://www.youtube.com/watch?v=tt2k8PGm-TI",
  "Be Alright": "https://youtu.be/I0czvJ_jikg?si=ehMwJoqKflgfPOY8"
}

conn=get_db_connection()

for song_name, yt_url in songurls.items():
    conn.execute("UPDATE songs SET yt_link = ? WHERE name= ?",(yt_url,song_name))

conn.commit()
conn.close()