from utils import get_db_connection



songurls={
   "God's Plan": "https://www.youtube.com/watch?v=xpVfcZ0ZcFM",
    "SAD!": "https://www.youtube.com/watch?v=yQFBKx6eq8s",
    "rockstar (feat. 21 Savage)": "https://www.youtube.com/watch?v=UceaB4D0jpo",
    "Psycho (feat. Ty Dolla $ign)": "https://www.youtube.com/watch?v=au2n7vvGv_c",
    "In My Feelings": "https://www.youtube.com/watch?v=DRS_PpOrUZ4",
    "Better Now": "https://www.youtube.com/watch?v=UYwF-jdcVjY",
    "I Like It": "https://www.youtube.com/watch?v=xTlNMmZKwpA",
    "One Kiss (with Dua Lipa)": "https://www.youtube.com/watch?v=DkeiKbqa02g",
    "IDGAF": "https://www.youtube.com/watch?v=Mgfe5tIQEl0",
    "FRIENDS": "https://www.youtube.com/watch?v=jzD_yyEw0M4",
    "Havana": "https://www.youtube.com/watch?v=HCjNJDN56LC",
    "Lucid Dreams": "https://www.youtube.com/watch?v=mzB1ip58Gts",
    "Nice For What": "https://www.youtube.com/watch?v=U9BwWKXjVaI",
    "Girls Like You (feat. Cardi B)": "https://www.youtube.com/watch?v=aJOTlE1K90k",
    "The Middle": "https://www.youtube.com/watch?v=M3mJkSqZbX4",
    "All The Stars (with SZA)": "https://www.youtube.com/watch?v=JQbjS0_ZfJ0",
    "no tears left to cry": "https://www.youtube.com/watch?v=ffxKSjUwKdU",
    "X": "https://www.youtube.com/watch?v=t_jHrHC5890",
    "Moonlight": "https://www.youtube.com/watch?v=DXSGKRY3Sss",
    "Look Alive (feat. Drake)": "https://www.youtube.com/watch?v=4Oo888Z7o04",
    "These Days (feat. Jess Glynne, Macklemore & Dan Caplen)": "https://www.youtube.com/watch?v=pkCyfBibIbI",
    "Te Bote - Remix": "https://www.youtube.com/watch?v=9jI-z9QN6g8",
    "Mine": "https://www.youtube.com/watch?v=Gc71AmT_O2k",
    "Youngblood": "https://www.youtube.com/watch?v=-RJSbO8JaIw",
    "New Rules": "https://www.youtube.com/watch?v=k2qgadSvNyU",
    "Shape of You": "https://www.youtube.com/watch?v=JGwWNGJdvx8",
    "Love Lies (with Normani)": "https://www.youtube.com/watch?v=xYtsL9gXpA4",
    "Meant to Be (feat. Florida Georgia Line)": "https://www.youtube.com/watch?v=zDo0H8Fm7d0",
    "Jocelyn Flores": "https://www.youtube.com/watch?v=FAucVNRx_mU",
    "Perfect": "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    "Taste (feat. Offset)": "https://www.youtube.com/watch?v=LJXv6P8eRE0",
    "Solo (feat. Demi Lovato)": "https://www.youtube.com/watch?v=8JnfKKrXgRA",
    "I Fall Apart": "https://www.youtube.com/watch?v=7a66clsl0m0",
    "Nevermind": "https://www.youtube.com/watch?v=nSDgHBxUbVQ",
    "Echame La Culpa": "https://www.youtube.com/watch?v=TyHvyGVs42U",
    "Eastside (with Halsey & Khalid)": "https://www.youtube.com/watch?v=KFof8aaUvXw",
    "Never Be the Same": "https://www.youtube.com/watch?v=Ph54wQG8ynk",
    "Wolves": "https://www.youtube.com/watch?v=cH4E_t3m3cA",
    "changes": "https://www.youtube.com/watch?v=f0bbDFRYD_A",
    "In My Mind": "https://www.youtube.com/watch?v=W9P_qUnMaFg",
    "River (feat. Ed Sheeran)": "https://www.youtube.com/watch?v=3BXDsVD6O10",
    "Dura": "https://www.youtube.com/watch?v=sGIm0-5R3SU",
    "SICKO MODE": "https://www.youtube.com/watch?v=6ONRf7h3Mdk",
    "Thunder": "https://www.youtube.com/watch?v=fKopy74weus",
    "Me Niego": "https://www.youtube.com/watch?v=yYByz-fbaV4",
    "Jackie Chan": "https://www.youtube.com/watch?v=O6reZ2X7r5M",
    "Finesse (Remix) [feat. Cardi B]": "https://www.youtube.com/watch?v=LsoLEjrDogU",
    "Back To You - From 13 Reasons Why": "https://www.youtube.com/watch?v=VY1eFxgRR-M",
    "Let You Down": "https://www.youtube.com/watch?v=fbHbTBP_u7U",
    "Call Out My Name": "https://www.youtube.com/watch?v=M4Zu04EE2Sg",
    "Ric Flair Drip (& Metro Boomin)": "https://www.youtube.com/watch?v=LPTlvQ1Zet0",
    "Happier": "https://www.youtube.com/watch?v=m7Bc3pLyij0",
    "Too Good At Goodbyes": "https://www.youtube.com/watch?v=J_ub7Etch2U",
    "Freaky Friday (feat. Chris Brown)": "https://www.youtube.com/watch?v=aLnZ1NQm2uk",
    "Believer": "https://www.youtube.com/watch?v=7wtfhZwyrcc",
    "FEFE (feat. Nicki Minaj & Murda Beatz)": "https://www.youtube.com/watch?v=V_MXGdSBbAI",
    "Rise": "https://www.youtube.com/watch?v=hEDvMglH82Y",
    "Body (feat. brando)": "https://www.youtube.com/watch?v=A7A_Y6hMepc",
    "XO TOUR Llif3": "https://www.youtube.com/watch?v=WrsFXgQk5UI",
    "Sin Pijama": "https://www.youtube.com/watch?v=zEf423kYfqk",
    "2002": "https://www.youtube.com/watch?v=Il-an3K9pjg",
    "Nonstop": "https://www.youtube.com/watch?v=7EGVtS996uU",
    "Fuck Love (feat. Trippie Redd)": "https://www.youtube.com/watch?v=JcW87SloHPM",
    "In My Blood": "https://www.youtube.com/watch?v=36tggrpRoJU",
    "Silence": "https://www.youtube.com/watch?v=Tx1sqYc3qas",
    "God is a woman": "https://www.youtube.com/watch?v=kHLHSlExFis",
    "Dejala que vuelva (feat. Manuel Turizo)": "https://www.youtube.com/watch?v=vVj17HhPZpY",
    "Flames": "https://www.youtube.com/watch?v=J7_9D1Tco88",
    "What Lovers Do": "https://www.youtube.com/watch?v=5X-Mrc2l1d0",
    "Taki Taki (with Selena Gomez, Ozuna & Cardi B)": "https://www.youtube.com/watch?v=ixkoVwKQaJg",
    "Let Me Go (with Alesso, Florida Georgia Line & watt)": "https://www.youtube.com/watch?v=l8S_mbyKq3I",
    "Feel It Still": "https://www.youtube.com/watch?v=pBkHHoOIIn8",
    "Pray For Me (with Kendrick Lamar)": "https://www.youtube.com/watch?v=K5xERXE7pxI",
    "Walk It Talk It": "https://www.youtube.com/watch?v=fGqdIPsh-ms",
    "Him & I (with Halsey)": "https://www.youtube.com/watch?v=SA7AIQw-7Ms",
    "Candy Paint": "https://www.youtube.com/watch?v=Je93wI6hK_Y",
    "Congratulations": "https://www.youtube.com/watch?v=SC4xMk96P_c",
    "1, 2, 3 (feat. Jason Derulo & De La Ghetto)": "https://www.youtube.com/watch?v=p79enmPHeZc",
    "Criminal": "https://www.youtube.com/watch?v=Dx0SGs0-s1I",
    "Plug Walk": "https://www.youtube.com/watch?v=m_6VvO6b0W8",
    "lovely (with Khalid)": "https://www.youtube.com/watch?v=V1Pl8CzNzCw",
    "Stir Fry": "https://www.youtube.com/watch?v=fGgS4C63Xes",
    "HUMBLE.": "https://www.youtube.com/watch?v=tvTRZJ-4EyI",
    "Vaina Loca": "https://www.youtube.com/watch?v=3Z1Xz7qg-f0",
    "Perfect Duet (Ed Sheeran & Beyoncé)": "https://www.youtube.com/watch?v=817P8W8-mGE",
    "Corazon (feat. Nego do Borel)": "https://www.youtube.com/watch?v=K_YvshAkaG0",
    "Young Dumb & Broke": "https://www.youtube.com/watch?v=7-q92k3DclM",
    "Siguelo Bailando": "https://www.youtube.com/watch?v=vPZbeonI5Fk",
    "Downtown": "https://www.youtube.com/watch?v=t_jHrHC5890",
    "Bella": "https://www.youtube.com/watch?v=O1m_fN7rF8c",
    "Promises (with Sam Smith)": "https://www.youtube.com/watch?v=kkLk2XWMBf8",
    "Yes Indeed": "https://www.youtube.com/watch?v=g-wXm6vD8_M",
    "I Like Me Better": "https://www.youtube.com/watch?v=BcqxLCb7xK4",
    "This Is Me": "https://www.youtube.com/watch?v=CjxugyZCfuw",
    "Everybody Dies In Their Nightmares": "https://www.youtube.com/watch?v=762A4_A9Hks",
    "Rewrite The Stars": "https://www.youtube.com/watch?v=R3fC-7vYAnM",
    "I Miss You (feat. Julia Michaels)": "https://www.youtube.com/watch?v=q97E_Wz31fA",
    "No Brainer": "https://www.youtube.com/watch?v=kxloC1MKTKI",
    "Dusk Till Dawn - Radio Edit": "https://www.youtube.com/watch?v=v=tt2k8PGm-TI",
    "Be Alright": "https://www.youtube.com/watch?v=JAZ-Z6kG0HY"
}
conn=get_db_connection()

for song_name, yt_url in songurls.items():
    conn.execute("UPDATE songs SET yt_link = ? WHERE name= ?",(yt_url,song_name))

conn.commit()
conn.close()